# _HTTP_PORT = [Puerto de exposición del API]
# _RUNMODE = [Mojo de ejecución del API]
# _Variables de la DB
# _PGUSER = [Usuario de DB en Postgres]
# _PGPASS = [Contraseña del usuario de la DB en Postgres]
# _PGHOST = [URL, IP, DOMINIO o ENDPOINT de la BD]
# _PGPORT = [Puerto de la DB]
# _PGDB = [Nombre de la base de datos]
# _PGSCHEMA = [Nombre del esquema de la BD]
#

appname = api_Crud_tienda
httpport = ${API_CRUD_GESTION_DEPORTIVA_HTTP_PORT}
runmode = ${API_CRUD_GESTION_DEPORTIVA_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true

# Definición de variables de entorno DB

Pguser = ${API_CRUD_GESTION_DEPORTIVA_PGUSER}
PGpass = ${API_CRUD_GESTION_DEPORTIVA_PGPASS}
PGhost = ${API_CRUD_GESTION_DEPORTIVA_PGHOST}
PGport = ${API_CRUD_GESTION_DEPORTIVA_PGPORT}
PGdb = ${API_CRUD_GESTION_DEPORTIVA_PGDB}
PGschema = ${API_CRUD_GESTION_DEPORTIVA_PGSCHEMA}

