# _HTTP_PORT= [PUERTO DE EXPOSICION DEL API]
# _RUN_MODE= [Modo de ejecucion del api]
# _variables de la DB
# _PGUSER = [usuario de postgres]
# _PGPASS = [Contraseña del usuario de la DB]
# _PGHOST = [URL, IP, DOMINI O ENDPOINT DE LA DB]
# _PGPORT = [Puerto de la DB]
# _PGDB = [Nombre de la base de datos]
# _PGSCHEMA = [Nombre de esquema de la base de datos] 

appname = YoPLAY-APIS-CRUD-BEEGO
httpport = ${YoPLAY-API-CRUD-BEEGO_HTTP_PORT}
runmode = ${YoPLAY-API-CRUD-BEEGO_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true

# DEFINICION DE VARIABLES DE ENTORNO

PGuser = ${YoPLAY-API-CRUD-BEEGO_PGUSER}
PGpass = ${YoPLAY-API-CRUD-BEEGO_PGPASS}
PGhost= ${YoPLAY-API-CRUD-BEEGO_PGHOST}
PGport= ${YoPLAY-API-CRUD-BEEGO_PGPORT}
PGdb= ${YoPLAY-API-CRUD-BEEGO_PGDB}
PGschema= ${YoPLAY-API-CRUD-BEEGO_PGSHCEMA}




