#_HTTP_PORT=[puerto de exposicion del api]
#_RUN_MODE=[modo de ejecucion del api]
#variables de la DB
#_PGUSER = [usuario de DB]
#_PGPASS = [contraseña deñ usuario de la db]
#_PGHOST = [URL, IP, DOMINIO o ENDPOINT de la DB]
#_PGPORT = [Puerto de la db]
#_PGDB = [nombre de la base de datos ]
#_PGSCHEMA =[Nombre del esquemas de base de base ]





appname = YoPLAY_APIS_CRUD_BEEGO_CLASE
httpport = ${YoPLAY_APIS_CRUD_BEEGO_CLASE_HTTP_PORT}
runmode = ${YoPLAY_APIS_CRUD_BEEGO_CLASE_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true


#Definicion de variables de entorno DB


PGuser=${YoPLAY_APIS_CRUD_BEEGO_CLASE_PGUSER}
PGpass= ${YoPLAY_APIS_CRUD_BEEGO_CLASE_PGPASS}
PGhost =${YoPLAY_APIS_CRUD_BEEGO_CLASE_PGHOST}
PGport = ${YoPLAY_APIS_CRUD_BEEGO_CLASE_PGPORT}
PGdb=${YoPLAY_APIS_CRUD_BEEGO_CLASE_PGDB}
PGschema=${YoPLAY_APIS_CRUD_BEEGO_CLASE_PGSCHEMA}
