# _HTTP_PORT= [PUERTO DE EXPOSICION DEL API]
# _RUN_MODE= [Modo de ejecucion del api]
# _variables de la DB
# _PGUSER = [usuario de postgres]
# _PGPASS = [Contraseña del usuario de la DB]
# _PGHOST = [URL, IP, DOMINI O ENDPOINT DE LA DB]
# _PGPORT = [Puerto de la DB]
# _PGDB = [Nombre de la base de datos]
# _PGSCHEMA = [Nombre de esquema de la base de datos] 

appname = YoPLAY-APIS-CRUD-BEEGO
httpport = ${YoPLAY_API_CRUD_BEEGO_HTTP_PORT}
runmode = ${YoPLAY_API_CRUD_BEEGO_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true

# DEFINICION DE VARIABLES DE ENTORNO

PGuser = ${YoPLAY_API_CRUD_BEEGO_PGUSER}
PGpass = ${YoPLAY_API_CRUD_BEEGO_PGPASS}
PGhost= ${YoPLAY_API_CRUD_BEEGO_PGHOST}
PGport= ${YoPLAY_API_CRUD_BEEGO_PGPORT}
PGdb= ${YoPLAY_API_CRUD_BEEGO_PGDB}
PGschema=${YoPLAY_API_CRUD_BEEGO_PGSCHEMA}

